# Loan data analysis using numpy

## Import Packages

In [849]:
import numpy as np

In [850]:
# to negulate scinific notaion in numeric dats
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

## import Data 

In [851]:
ld = np.genfromtxt(r"D:\Data sets\Udemy Practice\Data Cleaning & processing\loan-data.csv",
                   delimiter =';',
                   skip_header= True, 
                   autostrip= True)

In [852]:
ld

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [853]:
ld.shape

(10000, 14)

## Checking incomplete Data

In [854]:
np.isnan(ld).sum()

88005

In [855]:
temp_fill = np.nanmax(ld) +1
temp_mean = np.nanmean(ld,axis = 0)

C:\Users\Arunprakash Babu\AppData\Local\Temp\ipykernel_9972\522726117.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(ld,axis = 0)


In [856]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [857]:
temp_status = np.array([np.nanmin(ld, axis = 0), 
                        temp_mean, 
                        np.nanmax(ld, axis = 0)])
                        

C:\Users\Arunprakash Babu\AppData\Local\Temp\ipykernel_9972\3228149148.py:1: RuntimeWarning: All-NaN slice encountered
  temp_status = np.array([np.nanmin(ld, axis = 0),
C:\Users\Arunprakash Babu\AppData\Local\Temp\ipykernel_9972\3228149148.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(ld, axis = 0)])


In [858]:
temp_status

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting Data set

### Splitting the Columns

In [859]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [860]:
column_string = np.argwhere(np.isnan(temp_mean)).squeeze()
column_string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [861]:
column_numeric = np.argwhere(np.isnan(temp_mean) == False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

## Reimpoerting Dataset

In [862]:
lds = np.genfromtxt(r"D:\Data sets\Udemy Practice\Data Cleaning & processing\loan-data.csv",
                   delimiter =';',
                   skip_header= True, 
                   autostrip= True,
                   usecols = column_string,
                   dtype = 'str')

In [863]:
lds

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [864]:
ldn = np.genfromtxt(r"D:\Data sets\Udemy Practice\Data Cleaning & processing\loan-data.csv",
                   delimiter =';',
                   skip_header= True, 
                   autostrip= True,
                   usecols = column_numeric,
                   filling_values = temp_fill)

In [865]:
ldn

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [866]:
temp_fill

68616520.0

In [867]:
ld

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## The Columns Name 

In [868]:
ldcn = np.genfromtxt(r"D:\Data sets\Udemy Practice\Data Cleaning & processing\loan-data.csv",
                   delimiter =';', 
                   autostrip= True,
                   dtype = 'str')

In [869]:
ld_Column_Names = ldcn[0]

In [870]:
ld_Column_Names

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U69')

In [871]:
lds_Column_Names = ld_Column_Names[column_string]

In [872]:
ldn_Column_Names = ld_Column_Names[column_numeric]

In [873]:
lds_Column_Names

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U69')

In [874]:
ldn_Column_Names

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U69')

## Manipulating String Columns

In [875]:
lds_Column_Names

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U69')

In [876]:
lds_Column_Names[0] = 'issue_date'

In [877]:
lds_Column_Names

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U69')

### Issue Date column

In [878]:
lds[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [879]:
# Checking unique value
np.unique(lds[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [880]:
lds[:,0] = np.chararray.strip(lds[:,0],"-15")

In [881]:
np.unique(lds[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [882]:
# Change the month columns in to numeric meaning

In [883]:
months = np.array(['','Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 
                   'Oct', 'Nov', 'Dec'])

In [884]:
months

array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      dtype='<U3')

In [885]:
for i in range(13):
    lds[:,0] = np.where(lds[:,0] == months[i],
                         i,
                         lds[:,0])           

In [886]:
np.unique(lds[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status Column

In [887]:
lds_Column_Names

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U69')

In [888]:
lds[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [889]:
np.unique(lds[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [890]:
len(np.unique(lds[:,1]))

9

In [891]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [892]:
np.isin(lds[:,1] , status_bad) == True

array([False, False, False, ..., False, False, False])

In [893]:
#Assign 0 to bad statis 1 to good status

In [894]:
lds[:,1] = np.where(np.isin(lds[:,1] , status_bad),0,1)

In [895]:
lds[:,1]

array(['1', '1', '1', ..., '1', '1', '1'], dtype='<U69')

In [896]:
np.unique(lds[:,1])

array(['0', '1'], dtype='<U69')

### Term Column

In [897]:
lds_Column_Names

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U69')

In [898]:
lds[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [899]:
np.unique(lds[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [900]:
lds[:,2] = np.chararray.strip(lds[:,2]," months")

In [901]:
np.unique(lds[:,2])

array(['', '36', '60'], dtype='<U69')

In [902]:
# Assign the empty to highst value
lds[:,2] = np.where(lds[:,2] == '',60,lds[:,2])

In [903]:
np.unique(lds[:,2])

array(['36', '60'], dtype='<U69')

In [904]:
# Rename the column name 
lds_Column_Names[2] = 'term_months'

In [905]:
lds_Column_Names

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U69')

### Greade Column & Sub Grade Column

In [906]:
lds_Column_Names

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U69')

In [907]:
lds[:,3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], dtype='<U69')

In [908]:
np.unique(lds[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [909]:
# Revie of subgrade column 
lds[:,4]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [910]:
np.unique(lds[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

#### Filling Sub Grade

In [911]:
for i in np.unique(lds[:,3])[1:]:
    lds[:,4] = np.where((lds[:,4] == '') & (lds[:,3] == i),
                        i+'5',
                        lds[:,4])

In [912]:
np.unique(lds[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [913]:
# Checking the counts
np.unique(lds[:,4], return_counts =True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [914]:
lds[:,4] = np.where (lds[:,4] == '','H1',lds[:,4])

In [915]:
np.unique(lds[:,4], return_counts =True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9],
       dtype=int64))

#### Removing Grade 

In [916]:
# due to subgrade perfect to proceed further removing the grade column
lds = np.delete(lds,3,axis = 1)

In [917]:
lds[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [918]:
# dellete in column name
lds_Column_Names = np.delete(lds_Column_Names,3)

In [919]:
lds_Column_Names

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U69')

#### Converting Sub Grade

In [920]:
lds[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [921]:
# create dict for assing numbers to subgrade

In [922]:
# keys = list of sub grade 
keys = list(np.unique(lds[:,3]))
keys

['A1',
 'A2',
 'A3',
 'A4',
 'A5',
 'B1',
 'B2',
 'B3',
 'B4',
 'B5',
 'C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'D1',
 'D2',
 'D3',
 'D4',
 'D5',
 'E1',
 'E2',
 'E3',
 'E4',
 'E5',
 'F1',
 'F2',
 'F3',
 'F4',
 'F5',
 'G1',
 'G2',
 'G3',
 'G4',
 'G5',
 'H1']

In [923]:
#number of unique vaues
np.unique(lds[:,3]).shape[0]

36

In [924]:
# make the list values in unique sub grade
values = list(range(1,np.unique(lds[:,3]).shape[0]+1))
values

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36]

In [925]:
# create dict of keys and  Values 
dict_sub_grade = dict(zip(keys,values))
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [926]:
dict_sub_grade['H1']

36

In [927]:
# Assign the values to sub_grade column
for i in np.unique(lds[:,3]):
    lds[:,3] = np.where(lds[:,3] == i,
                        dict_sub_grade[i],
                        lds[:,3])

In [928]:
np.unique(lds[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification Status Column

In [929]:
lds_Column_Names

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U69')

In [930]:
lds[:,4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      dtype='<U69')

In [931]:
np.unique(lds[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [932]:
# Assign 0 and 1 in the column 
lds[:,4] = np.where((lds[:,4] == 'Source Verified') | (lds[:,4] == 'Verified'),
         1,
         0
        )

In [933]:
np.unique(lds[:,4])

array(['0', '1'], dtype='<U69')

### URL Column

In [934]:
lds_Column_Names

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U69')

In [935]:
lds[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [936]:
# Removing repeted words 
lds[:,5] =np.chararray.strip(lds[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [937]:
lds[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [938]:
ldn_Column_Names

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U69')

In [939]:
ldn[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [940]:
np.array_equal(lds[:,5].astype(dtype = np.int32),ldn[:,0].astype(dtype = np.int32))

True

In [941]:
#Both id and URL uniques are same so deleting the URL column

In [942]:
lds = np.delete(lds,5, axis = 1)

In [943]:
# delete the column name 
lds_Column_Names = np.delete(lds_Column_Names,5)

In [944]:
lds

array([['5', '1', '36', '13', '1', 'CA'],
       ['0', '1', '36', '5', '1', 'NY'],
       ['9', '1', '36', '10', '1', 'PA'],
       ...,
       ['6', '1', '36', '5', '1', 'CA'],
       ['4', '1', '36', '17', '1', 'OH'],
       ['12', '1', '36', '4', '0', 'IL']], dtype='<U69')

In [945]:
lds_Column_Names

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U69')

In [946]:
ld[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

### State Address column

In [947]:
lds_Column_Names

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U69')

In [948]:
lds[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [949]:
np.unique(lds[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [950]:
np.unique(lds[:,5]).size

50

In [951]:
np.unique(lds[:,5],return_counts = True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [952]:
state_name, state_count = np.unique(lds[:,5],return_counts = True)

In [953]:
state_count_sorted = np.argsort(-state_count)

In [954]:
state_name[state_count_sorted],state_count[state_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [955]:
lds[:,5] = np.where(lds[:,5]  == '',
                    0,
                    lds[:,5] )

In [956]:
# create group of states
state_west = np.array(['WA', 'OR', 'CA', 'NV', 'ID', 'MT', 'WY', 'UT', 'CO', 'AZ', 'NM', 'HI', 'AK'])

state_south = np.array(['TX', 'OK', 'AR', 'LA', 'MS', 'AL', 'TN', 'KY', 'FL', 'GA', 'SC', 'NC', 'VA', 'WV', 'MD', 'DE', 'DC'])

state_midwest = np.array(['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO', 'WI', 'IL', 'IN', 'MI', 'OH'])

state_east = np.array(['PA', 'NY', 'NJ', 'CT', 'MA', 'VT', 'NH', 'ME', 'RI'])

In [957]:
# Assigh the numeric values to the state group wise

In [958]:
lds[:,5] = np.where(np.isin(lds[:,5], state_west), 1, lds[:,5])

In [959]:
lds[:,5] = np.where(np.isin(lds[:,5], state_south), 2, lds[:,5])

In [960]:
lds[:,5] = np.where(np.isin(lds[:,5], state_midwest), 3, lds[:,5])

In [961]:
lds[:,5] = np.where(np.isin(lds[:,5], state_east), 4, lds[:,5])

In [962]:
lds[:,5]

array(['1', '4', '4', ..., '1', '3', '3'], dtype='<U69')

In [963]:
np.unique(lds[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [964]:
lds

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

### Converting to Numbers

In [965]:
lds

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [966]:
lds = lds.astype(np.int32)

In [967]:
lds

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

## Manipulating Numeric dataset columns

In [968]:
ldn

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [969]:
np.isnan(ldn).sum()

0

### Substitute "Filler" Values

In [970]:
ldn_Column_Names

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U69')

#### ID Column

In [971]:
ldn[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [972]:
temp_fill

68616520.0

In [973]:
np.isin(ldn[:,0],temp_fill).sum()

0

### Temporary status 

In [974]:
temp_status[:, column_numeric]
# Having 
# min 
# mean
# max
# values 

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

### Funded Amount

In [975]:
ldn_Column_Names

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U69')

In [976]:
ldn[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [977]:
ldn[:,2] = np.where(ldn[:,2] == temp_fill,
         temp_status[0, column_numeric[2]],
         ldn[:,2])
ldn[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

### Loaned amunt, Intrest Rate, Total Payment, Instalment Columns

In [978]:
# Assign Max values

In [979]:
ldn_Column_Names

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U69')

In [982]:
for i in [1,3,4,5]:
    ldn[:,i] = np.where(ldn[:,i] == temp_fill,
         temp_status[2, column_numeric[i]],
         ldn[:,i])

In [983]:
ldn

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

## Currency Change 

### The Exchange Rate

In [989]:
# import data of the 2015 euro to dolllar file  we only need 4 th column due to closing price
EUR_USD = np.genfromtxt(r"D:\Data sets\Udemy Practice\Data Cleaning & processing\EUR-USD.csv", 
                        delimiter = ',',
                        autostrip = True,
                        skip_header= True,
                        usecols= 3)

In [990]:
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [991]:
lds

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [992]:
lds_Column_Names

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U69')

In [994]:
exchange_rate = lds[:,0]
exchange_rate

array([ 5,  0,  9, ...,  6,  4, 12])

In [997]:
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)

In [999]:
exchange_rate = np.where(exchange_rate == 0,
                         np.mean(EUR_USD),
                         exchange_rate)

In [1000]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [1001]:
exchange_rate.shape

(10000,)

In [1002]:
ldn.shape

(10000, 6)

In [1004]:
exchange_rate = np.reshape(exchange_rate,(10000,1))

In [1005]:
exchange_rate

array([[1.1 ],
       [1.11],
       [1.13],
       ...,
       [1.12],
       [1.11],
       [1.09]])

In [1008]:
# Merge 2 array in single
ldn = np.hstack((ldn,exchange_rate))

In [1009]:
ldn

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [1013]:
# add column name in to exist one 
ldn_Column_Names = np.concatenate((ldn_Column_Names, np.array(['exchange_rate'])))

In [1014]:
ldn_Column_Names

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U69')

## From USD to EUR

In [1016]:
ldn_Column_Names

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U69')

In [1017]:
columns_dollar = np.array([1,2,4,5])

In [1019]:
ldn[:,[columns_dollar]]

array([[[35000.  , 35000.  ,  1184.86,  9452.96]],

       [[30000.  , 30000.  ,   938.57,  4679.7 ]],

       [[15000.  , 15000.  ,   494.86,  1969.83]],

       ...,

       [[10000.  , 10000.  ,  1372.97,  2185.64]],

       [[35000.  , 10000.  ,   354.3 ,  3199.4 ]],

       [[10000.  , 10000.  ,   309.97,   301.9 ]]])

In [1020]:
ldn[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [1029]:
for i in columns_dollar:
    ldn = np.hstack((ldn, np.reshape( ldn[:,i] / ldn[:,6] , (10000,1))))

In [1030]:
ldn

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [1031]:
ldn.shape

(10000, 11)

### Expanding Header

In [1032]:
ldn_Column_Names

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U69')

In [1037]:
ldn_Column_Names_additional = np.array([column_name + '_EUR' for column_name in ldn_Column_Names[columns_dollar]])

In [1038]:
ldn_Column_Names_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [1041]:
ldn_Column_Names = np.concatenate((ldn_Column_Names, ldn_Column_Names_additional))

In [1042]:
ldn_Column_Names

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U69')

In [1047]:
ldn_Column_Names[columns_dollar] = np.array([column_name + '_USD' for column_name in ldn_Column_Names[columns_dollar]])

In [1048]:
ldn_Column_Names

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U69')

In [1049]:
column_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [1051]:
ldn_Column_Names = ldn_Column_Names[column_index_order]

In [1052]:
ldn_Column_Names

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U69')

In [1055]:
ldn = ldn[:,column_index_order]

In [1056]:
ldn

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

## Intrest rate column

In [1057]:
ldn_Column_Names

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U69')

In [1058]:
ldn[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [1060]:
ldn[:,5] = ldn[:,5]/100

In [1061]:
ldn[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

## Complete the Dataset

In [1063]:
lds.shape

(10000, 6)

In [1065]:
ldn.shape

(10000, 11)

In [1067]:
# Combine the datasets 
loan_data = np.hstack((ldn,lds))

In [1069]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [1070]:
np.isnan(loan_data).sum()

0

In [1073]:
# Combine columns
loan_data_Column_Names = np.concatenate((ldn_Column_Names,lds_Column_Names))

In [1074]:
loan_data_Column_Names

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U69')

### Sorting the new Data set

In [1076]:
# sort acorting to loan Id 
np.sort(loan_data[:,0])

array([  373332.,   575239.,   707689., ..., 68614880., 68615915., 68616519.])

In [1081]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [1082]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [1083]:
loan_data.shape

(10000, 17)

In [1085]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

### Storing the Dataset

In [1087]:
loan_data = np.vstack((loan_data_Column_Names,loan_data))

In [1088]:
loan_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'addr_state'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U69')

In [1091]:
np.savetxt(r"D:\Data sets\Udemy Practice\Data Cleaning & processing\Loan-data-preprossed.csv", 
           loan_data, 
           fmt = "%s", 
           delimiter = ',')